GET http://localhost:3001/api/denuncias/
content-type: application/json

{
    "titulo": "part3",
    "denunciado": "Wed, 21 Oct 2015 18:27:50 GMT",
    "caracteristicas": "papas",
    "codigo": "codigo"
}