POST http://localhost:3001/api/denuncias/
content-type: application/json

{
    "titulo": "ernest2",
    "denunciado": "alej4314123andro",
    "caracteristicas": "me r3obo papas",
  
    "folio":"trece",
    "contra":"contrasena1234"
}

